spring:
  application:
    name: marketing-service
  config:
    import: ${CONFIG_IMPORT:optional:configserver:http://localhost:8888/}

logging:
  level:
    org.springframework.cloud.config.client: DEBUG