export const shippingData = [
    {
      method: "InPost - Parcel Locker 24/7",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Below 60 $",
      deliveryCost: "4 $",
      cod: "No COD available",
    },
    {
      method: "InPost - Parcel Locker 24/7",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Above 60 $",
      deliveryCost: "FREE",
      cod: "No COD available",
    },
    {
      method: "InPost - Courier",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Below 60 $",
      deliveryCost: "4 $",
      cod: "+ 5,00 zł",
    },
    {
      method: "InPost - Courier",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Above 60 $",
      deliveryCost: "FREE",
      cod: "+ 1,50 $",
    },
    {
      method: "InPost - Weekend Package",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Below 60 $",
      deliveryCost: "4,50 $",
      cod: "No COD available",
    },
    {
      method: "InPost - Weekend Package",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Above 60 $",
      deliveryCost: "2,50 $",
      cod: "No COD available",
    },
    {
      method: "DPD - Courier",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Below 60 $",
      deliveryCost: "4 $",
      cod: "+ 1,50 $",
    },
    {
      method: "DPD - Courier",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Above 60 $",
      deliveryCost: "FREE",
      cod: "+ 1,50 $",
    },
    {
      method: "DPD Pickup + ParcelPoint",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Below 60 $",
      deliveryCost: "2,50 $",
      cod: "No COD available",
    },
    {
      method: "DPD Pickup + ParcelPoint",
      processingTime: "1-2 business days",
      deliveryTime: "24h on business days",
      orderValue: "Above 60 $",
      deliveryCost: "FREE",
      cod: "No COD available",
    },
    {
      method: "Personal collection in the store",
      processingTime: "1-2 business days",
      deliveryTime: "2-3 business days",
      orderValue: "All orders",
      deliveryCost: "FREE",
      cod: "FREE",
    },
  ];