spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SEARCH_LOCATIONS}

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"