server:
  port: 8070
  servlet:
    context-path: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: ${ZIPKIN_URL}/api/v2/spans
      base-url: ${ZIPKIN_URL}
      connect-timeout: 10s
      read-timeout: 30s

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      retry:
        enabled: true
        max-attempts: 5
        interval: 1s
        backoff-policy: EXPONENTIAL

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG